### ISSUE TITLE
Tracking: React Native SDK v1.0

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#14]
### Requirements

Create a  `xmtp-react-native` that mirrors `xmtp-js` functionality and demonstrate core functionality in a React Native sample app.

### Prerequisites  

- [x] `ios-xmtp` as a cocoapod
    - [x] swift-gRPC does not support cocoapods so needs to be replaced with rust
    - [x] GigaBitcoin/secp256k1 does not support cocoapods so needs to be replaced with rust
    - [x] SwiftNIO does not support cocoapods so needs to be replaced with rust

### Developer Preview

- [ ] Create a native bridge to iOS and Android
    - [x] Add authentication to match xmtp-js
    - [x] Wrap xmtp in a`xmtp.Client` (like `xmtp-js`)
    - [ ] Reproduce utility classes/methods
        - [x] Client
           - [x] createRandom()
           - [x] create()
           - [x] [canMessage()](https://github.com/xmtp/xmtp-react-native/issues/8)
           - [ ] more clientOptions
        - [x] Conversations
           - [x] list()
           - [x] stream()
           - [x] newConversation()
           - [x] [streamAllMessages()](https://github.com/xmtp/xmtp-react-native/issues/9)
        - [x] Conversation
           - [x] messages()
             - [x] [paginate messages](https://github.com/xmtp/xmtp-react-native/issues/6)
           - [x] send()
           - [x] streamMessages()
           - [x] peerAddress
           - [x] decodeEnvelope
        - [x] DecodedMessage
        - [x] EnvelopeBuilder
    - [x] Publish npm library 
- [x] Publish repo README covering Dev Preview features and with Dev Preview badge

### GA

 - [x] Integrated with a third party app
    - [x] Successfully received push notifications
 - [x] Publish repo README with GA badge
 - [x] Reference docs for SDK GA

### Nice to have

- [x] [Write tests](https://github.com/xmtp/xmtp-react-native/issues/3)
- [ ] [Clean up streams](https://github.com/xmtp/xmtp-react-native/issues/1) 
- [ ] [Clean up exports](https://github.com/xmtp/xmtp-react-native/issues/11)
- [x] Create example app
    - [x] Use xmtp-react-native to demonstrate SDK
        - [x] Initialize client with a signer
        - [x] List conversations
        - [x] List messages
        - [x] Send messages
        - [x] Stream conversations
        - [x] Stream messages
        - [x] Wallet Connect
        - [ ] [Push notifications](https://github.com/xmtp/xmtp-react-native/issues/22)
        - [ ] [Local DB Caching](https://github.com/xmtp/xmtp-react-native/issues/5)
         
### Decision log

[April 12, 2023] 
- In an effort to move the xmpt-iOS SDK into a cocoapod to support the native bridge we will be making an effort to pull unsupported cocoapod support into a rust library. You can read more about React Native Bridge and Swift Package Manager here: https://github.com/react-native-community/discussions-and-proposals/issues/587
- As a stop gap we will be releasing a new [react native quick starter app ](https://github.com/xmtp/xmtp-quickstart-react-native) that shows a simple webview implementation that calls through to `xmpt-js`.

**Comment by yash-luna** [comment]
- [ ]

**Comment by nplasterer** [comment]
Released publicly October 24th 2023.
