### ISSUE TITLE
Tracking: RN Group Chat - Alpha

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#213]
### RN Android

- [ ] Reproduce utility classes/methods
  - [ ] Client
    - [x] update existing `create` method on client to also create a `FfiXmtpClient`
    - [ ] Existing client should now also have a `FfiLogger`
    - [x] Have existing SigningKey extend `FfiInboxOwner` so it can be used to create both V2 and V3 clients
    - [x] If `FfiXmtpClient` exists get address from `account_address()`
    - [ ] If `FfiXmtpClient` exists store a reference to `installation_id()`
    - [ ] Conversations on client should also take a `libXMTPConversations`
    - [x] If `FfiXmtpClient` exists client create should call `register_identity`
    - [ ] Ability to `list_my_installations()`
    - [ ] Ability to `revoke_installation()`
  - [ ] Conversations
    - [x] Should be able to create a group `newGroup()` -- `create_group()`
    - [x] Should be able to list just groups `listGroups` -- `libXMTPConversations.list()`
    - [x] Should be able to list an ordered list of conversations & groups `list(includeGroups: Boolean = false)`
    - [x] Should be able to stream groups `libXMTPConversations.stream()`
    - [x] Should be able to stream both conversations & groups `stream(includeGroups:Boolean = false)`
    - [x] Should be able to `sync` groups so that the libxmtp database gets updated
    - [x] Should be able to stream all messages from both groups and conversations (`streamAllMessages(includeGroups: Boolean = false)`
  - [ ] Conversation/Group methods
    - [x] Should have a unique identifier of the conversation `id()` equivalent to existing topic
    - [ ] Should be able to `send()` messages of any content type
    - [x] Should be able to resync the libxmtp database `sync()`
    - [x] Should be able to list messages `find_messages()` as Decoded and Decrypted Messages
    - [x] Should be able to list members `list_members()`
    - [x] Should be able to add members `add_members()`
    - [x] Should be able to remove members `remove_members()`
    - [x] Should be able to stream messages `stream()`
    - [ ] Should be able to leave a group `leave()`
    - [x] Can check if a message can be sent `can_message()`
- [ ] Publish repo README covering Dev Preview features and with Dev Preview badge

### RN iOS

- [ ] Reproduce utility classes/methods
  - [ ] Client
    - [x] update existing `create` method on client to also create a `FfiXmtpClient`
    - [ ] Existing client should now also have a `FfiLogger`
    - [ ] Have existing SigningKey extend `FfiInboxOwner` so it can be used to create both V2 and V3 clients
    - [x] If `FfiXmtpClient` exists get address from `account_address()`
    - [ ] If `FfiXmtpClient` exists store a reference to `installation_id()`
    - [ ] Conversations on client should also take a `libXMTPConversations`
    - [x] If `FfiXmtpClient` exists client create should call `register_identity`
    - [ ] Ability to `list_my_installations()`
    - [ ] Ability to `revoke_installation()`
  - [ ] Conversations
    - [x] Should be able to create a group `newGroup()` -- `create_group()`
    - [x] Should be able to list just groups `listGroups` -- `libXMTPConversations.list()`
    - [x] Should be able to list an ordered list of conversations & groups `list(includeGroups: Boolean = false)`
    - [x] Should be able to stream groups `libXMTPConversations.stream()`
    - [x] Should be able to stream both conversations & groups `stream(includeGroups:Boolean = false)`
    - [x] Should be able to `sync` groups so that the libxmtp database gets updated
    - [x] Should be able to stream all messages from both groups and conversations (`streamAllMessages(includeGroups: Boolean = false)`
  - [ ] Conversation/Group methods
    - [x] Should have a unique identifier of the conversation `id()` equivalent to existing topic
    - [ ] Should be able to `send()` messages of any content type
    - [x] Should be able to resync the libxmtp database `sync()`
    - [x] Should be able to list messages `find_messages()` as Decoded and Decrypted Messages
    - [x] Should be able to list members `list_members()`
    - [x] Should be able to add members `add_members()`
    - [x] Should be able to remove members `remove_members()`
    - [x] Should be able to stream messages `stream()`
    - [ ] Should be able to leave a group `leave()`
    - [x] Can check if a message can be sent `can_message()`
- [ ] Publish repo README covering Dev Preview features and with Dev Preview badge

### GA - [Targeting March 30, 2024]

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA
 
### Docs
Docs are currently being drafted documents for a PR. You can check the progress made so far by visiting the [preview link](https://junk-range-possible-git-groupchats-xmtp-labs.vercel.app/docs/build/groups). For more information on the PR itself, you can check https://github.com/xmtp/xmtp-dot-org/pull/650.

### Nice to have

- [ ] Create sample app
    - [ ] Use SDK to demonstrate
        - [x] Initialize client
        - [x] List conversations
        - [x] List messages
        - [x] Send messages
        - [x] Stream conversations
        - [ ] Stream messages
        - [ ] Wallet Connect
        - [ ] Group Chat
          - [x] send messages (any content type)
          - [x] add member
          - [x] remove member
          - [x] list members
          - [ ] leave

**Comment by peterferguson** [comment]
Hey just wondering whether this group implementation will also include a `conversationID` similar to the v2 conversations?

**Comment by humanagent** [comment]
Hey @peterferguson, the `conversationID` is no longer available for 1:1 conversations. It has been removed from all the SDKs and is not part of the group chat specifications either.

**Comment by alexrisch** [comment]
~~Issue:
It looks like the messages method on group is returning a json string rather than a DecodedMessage, I might have fixed it with https://github.com/xmtp/xmtp-react-native/pull/245, but haven't verified~~

**Comment by alexrisch** [comment]
Issue:
Client.createFromKeyBundle and Client.create errors when attempting to use functionality enabled by groups, example: client.conversations.newGroup()

Repro:
```
  const aliceClient = await Client.createRandom({
    env: 'local',
    enableAlphaMls: true
  })
  const key = await aliceClient.exportKeyBundle()
  const aliceKeyClient = await Client.createFromKeyBundle(key, {
    env: 'dev',
    enableAlphaMls: true
  })
  // Errors when Alice creates a group
  const aliceGroup = await aliceKeyClient.conversations.newGroup(
    [...]
  )
```

**Comment by alexrisch** [comment]
~~Feature: Export Group type~~

**Comment by alexrisch** [comment]
Is prepareMessage needed for groups?

**Comment by nplasterer** [comment]
prepareMessage doesn't seem necessary because of the local database. Messages you send show instantly without the need to prepare them.

**Comment by nplasterer** [comment]
Here are some requests for more functionality 

- [ ] Prepare message functionality
- [ ] How to handle push notifications for welcomes and existing groups
    - How to fetch just a group
    - Can they pass there own database url so they can manage it
- [x] StreamAllMessages @richardhuaaa (rust)
- [x] A way to find out who the group admin is - @neekolas (rust) & @nplasterer (native + RN)
- [x] Expose pagination on messages in RN - @nplasterer (RN)
- [x] Setting DB URL & encryption Key
- [x] listBatchMessages functionality
- [ ] Group protocol consent - Scott (native)
- [ ] Groups frames
- [x] Ability to "logout" aka delete local database

**Comment by neekolas** [comment]
I can handle the "find out who the group admin is", which I'm going to interpret as a broader "tell me what this groups permissions are, and where I fit into them".

Will get to groups frames some time later.

**Comment by nplasterer** [comment]
Closing this in favor of the new issue to track our movement towards prod
https://github.com/xmtp/xmtp-react-native/issues/309
