### ISSUE TITLE
Tracking: Group Chat - Prod (React Native)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-react-native#309]
### Must have
- [x] #312
- [x] Filter out group message kind https://github.com/xmtp/libxmtp/issues/522
- [x] Push Notifications https://github.com/xmtp/libxmtp/issues/527
- [x] Streaming 
  - [x] #328
  - [x] #329
- [x] Group Chat Names https://github.com/xmtp/libxmtp/issues/548
- [x] Who added me in a group https://github.com/xmtp/xmtp-react-native/issues/321
- [x] Message send state https://github.com/xmtp/libxmtp/issues/516
- [x] #332
- [x] #330
- [x] Inbox Id Consent

### Polish/Bugs
- [x] https://github.com/xmtp/xmtp-react-native/issues/356
- [x] https://github.com/xmtp/xmtp-react-native/issues/355
- [x] https://github.com/xmtp/xmtp-react-native/issues/351
- [x] https://github.com/xmtp/xmtp-react-native/issues/378
- [x] https://github.com/xmtp/xmtp-react-native/issues/380
- [x] https://github.com/xmtp/xmtp-react-native/issues/386
- [x] https://github.com/xmtp/xmtp-react-native/issues/392
- [x] https://github.com/xmtp/xmtp-react-native/issues/394
- [x] https://github.com/xmtp/xmtp-react-native/issues/391
- [ ] https://github.com/xmtp/xmtp-react-native/issues/401

### Nice to have
- [ ] Ability to `list_my_installations()`
- [ ] Ability to `revoke_installation()`
- [ ] Leave https://github.com/xmtp/libxmtp/issues/441
- [x] #333
- [x] #331
- [ ] Consent Proof Handling
- [ ] HMACs https://github.com/xmtp/libxmtp/issues/422
- [ ] Stream Groups (groups and convos) https://github.com/xmtp/libxmtp/issues/504
